name: My First Wirkflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-slim

    steps:
      - name: print a welcome message
        run echo "Welcome To My First GitHub Action Workflow!"
